from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'marker not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old, new, 1))

# This script is intentionally small and deterministic; it is removed by the
# production commit after the Flutter analyzer passes.
replace_once('lib/widgets/ojs_video_page.dart',
    "  bool _isSpeedBoosted = false;\n",
    "  bool _isSpeedBoosted = false;\n  bool _clearDisplay = false;\n  bool _isCaptionExpanded = false;\n")
replace_once('lib/widgets/ojs_video_page.dart',
    "  void _start2xSpeed() {\n    if (_controller == null || !_isInit) return;\n    HapticFeedback.mediumImpact();\n    setState(() => _isSpeedBoosted = true);\n    _controller?.setPlaybackSpeed(2.0);\n  }\n\n  void _resetSpeed() {\n    if (_isSpeedBoosted && _controller != null && _isInit) {\n      setState(() => _isSpeedBoosted = false);\n      _controller?.setPlaybackSpeed(1.0);\n    }\n  }\n",
    "  Future<void> _openGestureOptions() async {\n    if (_controller == null || !_isInit) return;\n    HapticFeedback.mediumImpact();\n    final selected = await showModalBottomSheet<String>(\n      context: context,\n      backgroundColor: const Color(0xFF13171D),\n      shape: const RoundedRectangleBorder(\n        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),\n      ),\n      builder: (sheetContext) => SafeArea(\n        child: Column(\n          mainAxisSize: MainAxisSize.min,\n          children: [\n            const SizedBox(height: 10),\n            const Text(\n              'Playback & Display',\n              style: TextStyle(color: Colors.white, fontSize: 17, fontWeight: FontWeight.w800),\n            ),\n            const SizedBox(height: 10),\n            const Padding(\n              padding: EdgeInsets.symmetric(horizontal: 20),\n              child: Align(\n                alignment: Alignment.centerLeft,\n                child: Text('Playback Speed', style: TextStyle(color: Colors.white54, fontSize: 12)),\n              ),\n            ),\n            const SizedBox(height: 4),\n            Row(\n              mainAxisAlignment: MainAxisAlignment.spaceEvenly,\n              children: [\n                _speedChip(sheetContext, '1x', 1.0),\n                _speedChip(sheetContext, '1.5x', 1.5),\n                _speedChip(sheetContext, '2x', 2.0),\n              ],\n            ),\n            const SizedBox(height: 8),\n            ListTile(\n              leading: const Icon(Icons.visibility_off_rounded, color: Colors.white70),\n              title: const Text('Clear Display', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w700)),\n              subtitle: const Text('Hide feed controls temporarily', style: TextStyle(color: Colors.white54)),\n              trailing: Switch(\n                value: _clearDisplay,\n                onChanged: (value) => Navigator.pop(sheetContext, value ? 'clear_on' : 'clear_off'),\n              ),\n            ),\n            const SizedBox(height: 8),\n          ],\n        ),\n      ),\n    );\n    if (!mounted) return;\n    if (selected == 'clear_on') {\n      setState(() => _clearDisplay = true);\n    } else if (selected == 'clear_off') {\n      setState(() => _clearDisplay = false);\n    }\n  }\n\n  Widget _speedChip(BuildContext context, String label, double speed) {\n    return ActionChip(\n      label: Text(label),\n      labelStyle: const TextStyle(color: Colors.white, fontWeight: FontWeight.w800),\n      backgroundColor: const Color(0xFF222831),\n      side: const BorderSide(color: Colors.white10),\n      onPressed: () {\n        _controller?.setPlaybackSpeed(speed);\n        setState(() => _isSpeedBoosted = speed == 2.0);\n        Navigator.pop(context);\n      },\n    );\n  }\n")
replace_once('lib/widgets/ojs_video_page.dart',
    "        onTap: _togglePlayPause,\n        onDoubleTap: _handleDoubleTap,\n        onLongPressStart: (_) => _start2xSpeed(),\n        onLongPressEnd: (_) => _resetSpeed(),\n        onLongPressCancel: () => _resetSpeed(),\n",
    "        onTap: () {\n          if (_clearDisplay) {\n            setState(() => _clearDisplay = false);\n          }\n          _togglePlayPause();\n        },\n        onDoubleTap: _handleDoubleTap,\n        onLongPress: _openGestureOptions,\n")

# Hide every existing UI overlay while keeping the actual video + GestureDetector active.
for marker in [
    "            // 2. Play/Pause Big Center Indicator\n",
    "            // 3. Double Tap Heart Pop Animation\n",
    "            // 4. 2X Playback Speed Top Minimal Banner\n",
    "            // 5. TikTok 16:9 Landscape Fullscreen Button\n",
    "            // 6. Right Action Rail\n",
    "            // 7. Bottom Metadata\n",
    "            // 8. Interactive Timeline Video Scrubber (Bottom Line)\n",
]:
    replacement = marker + "            if (!_clearDisplay)\n"
    replace_once('lib/widgets/ojs_video_page.dart', marker, replacement)

old = """                  Text(\n                    widget.video.caption,\n                    maxLines: 2,\n                    overflow: TextOverflow.ellipsis,\n                    style: const TextStyle(\n                      color: Colors.white,\n                      fontSize: 13,\n                      height: 1.3,\n                      fontWeight: FontWeight.w400,\n                    ),\n                  ),\n                  const SizedBox(height: 6),\n                  GestureDetector(\n                    onTap: _openSoundHub,\n                    child: Row(\n                      children: [\n                        const Icon(\n                          Icons.music_note_rounded,\n                          color: Colors.white70,\n                          size: 13,\n                        ),\n                        const SizedBox(width: 4),\n                        Expanded(\n                          child: Text(\n                            'Original Audio - ${widget.video.creator} • OJAS Sound Studio',\n                            maxLines: 1,\n                            overflow: TextOverflow.ellipsis,\n                            style: const TextStyle(\n                              color: Colors.white70,\n                              fontSize: 11.5,\n                              fontWeight: FontWeight.w500,\n                            ),\n                          ),\n                        ),\n                      ],\n                    ),\n                  ),\n"""
new = """                  Text(\n                    widget.video.caption,\n                    maxLines: _isCaptionExpanded ? 8 : 2,\n                    overflow: _isCaptionExpanded ? TextOverflow.visible : TextOverflow.ellipsis,\n                    style: const TextStyle(\n                      color: Colors.white,\n                      fontSize: 13,\n                      height: 1.3,\n                      fontWeight: FontWeight.w400,\n                    ),\n                  ),\n                  if (widget.video.caption.length > 90)\n                    GestureDetector(\n                      onTap: () => setState(() => _isCaptionExpanded = !_isCaptionExpanded),\n                      child: Padding(\n                        padding: const EdgeInsets.only(top: 3),\n                        child: Text(\n                          _isCaptionExpanded ? 'See less' : '...See more',\n                          style: const TextStyle(color: Colors.white70, fontSize: 11.5, fontWeight: FontWeight.w700),\n                        ),\n                      ),\n                    ),\n                  const SizedBox(height: 6),\n                  GestureDetector(\n                    onTap: _openSoundHub,\n                    child: SingleChildScrollView(\n                      scrollDirection: Axis.horizontal,\n                      physics: const BouncingScrollPhysics(),\n                      child: Row(\n                        mainAxisSize: MainAxisSize.min,\n                        children: [\n                          const Icon(Icons.music_note_rounded, color: Colors.white70, size: 13),\n                          const SizedBox(width: 4),\n                          Text(\n                            'Original Audio - @${widget.video.creator}',\n                            maxLines: 1,\n                            style: const TextStyle(color: Colors.white70, fontSize: 11.5, fontWeight: FontWeight.w500),\n                          ),\n                          const SizedBox(width: 18),\n                        ],\n                      ),\n                    ),\n                  ),\n"""
replace_once('lib/widgets/ojs_video_page.dart', old, new)
